-- MySQL Script generated by MySQL Workbench
-- 06/29/15 09:13:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tblLieferant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblLieferant` (
  `Lieferant_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `Strasse` VARCHAR(45) NULL COMMENT '',
  `PLZ` INT NULL COMMENT '',
  `Ansprechpartner` VARCHAR(45) NULL COMMENT '',
  `URL` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`Lieferant_ID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblRaum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblRaum` (
  `Raum_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Bezeichnung` VARCHAR(45) NULL COMMENT '',
  `Notiz` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`Raum_ID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblKomponentenart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblKomponentenart` (
  `Art_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Bezeichnung` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`Art_ID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblKomponent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblKomponent` (
  `Komponent_ID` INT NOT NULL COMMENT '',
  `Lieferant_ID` INT NOT NULL COMMENT '',
  `Raum_ID` INT NOT NULL COMMENT '',
  `Art_ID` INT NOT NULL COMMENT '',
  `Hersteller` VARCHAR(45) NULL COMMENT '',
  `Notiz` VARCHAR(45) NULL COMMENT '',
  `Einkaufsdatum` DATE NULL COMMENT '',
  `Gewährleistungsdauer` INT NULL COMMENT '',
  PRIMARY KEY (`Komponent_ID`)  COMMENT '',
  INDEX `fk_tblKomponent_tblLieferant_idx` (`Lieferant_ID` ASC)  COMMENT '',
  INDEX `fk_tblKomponent_tblRaum1_idx` (`Raum_ID` ASC)  COMMENT '',
  INDEX `fk_tblKomponent_tblKomponentenart1_idx` (`Art_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_tblKomponent_tblLieferant`
    FOREIGN KEY (`Lieferant_ID`)
    REFERENCES `mydb`.`tblLieferant` (`Lieferant_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblKomponent_tblRaum1`
    FOREIGN KEY (`Raum_ID`)
    REFERENCES `mydb`.`tblRaum` (`Raum_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblKomponent_tblKomponentenart1`
    FOREIGN KEY (`Art_ID`)
    REFERENCES `mydb`.`tblKomponentenart` (`Art_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblVorgansart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblVorgansart` (
  `Vorgang_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Bezeichnung` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`Vorgang_ID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblKomponentenattribut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblKomponentenattribut` (
  `Attribut_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Bezeichnung` VARCHAR(45) NULL COMMENT '',
  `Einheit` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`Attribut_ID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblZulaessiger_Wert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblZulaessiger_Wert` (
  `Wert_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Von` INT NULL COMMENT '',
  `Bis` INT NULL COMMENT '',
  `Schrittweite` INT NULL COMMENT '',
  `Attribut_ID` INT NULL COMMENT '',
  PRIMARY KEY (`Wert_ID`)  COMMENT '',
  INDEX `fk_tblZulaessiger_Wert_tblKomponentenattribut1_idx` (`Attribut_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_tblZulaessiger_Wert_tblKomponentenattribut1`
    FOREIGN KEY (`Attribut_ID`)
    REFERENCES `mydb`.`tblKomponentenattribut` (`Attribut_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblZuordnung_Komp_Vorgang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblZuordnung_Komp_Vorgang` (
  `Komponent_ID` INT NOT NULL COMMENT '',
  `Vorgang_ID` INT NOT NULL COMMENT '',
  `Datum` DATE NULL COMMENT '',
  PRIMARY KEY (`Komponent_ID`, `Vorgang_ID`)  COMMENT '',
  INDEX `fk_tblKomponent_has_tblVorgansart_tblVorgansart1_idx` (`Vorgang_ID` ASC)  COMMENT '',
  INDEX `fk_tblKomponent_has_tblVorgansart_tblKomponent1_idx` (`Komponent_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_tblKomponent_has_tblVorgansart_tblKomponent1`
    FOREIGN KEY (`Komponent_ID`)
    REFERENCES `mydb`.`tblKomponent` (`Komponent_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblKomponent_has_tblVorgansart_tblVorgansart1`
    FOREIGN KEY (`Vorgang_ID`)
    REFERENCES `mydb`.`tblVorgansart` (`Vorgang_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblZuordnung_Art_Attr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblZuordnung_Art_Attr` (
  `Art_ID` INT NOT NULL COMMENT '',
  `Attribut_ID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Art_ID`, `Attribut_ID`)  COMMENT '',
  INDEX `fk_tblKomponentenart_has_tblKomponentenattribut_tblKomponen_idx` (`Attribut_ID` ASC)  COMMENT '',
  INDEX `fk_tblKomponentenart_has_tblKomponentenattribut_tblKomponen_idx1` (`Art_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_tblKomponentenart_has_tblKomponentenattribut_tblKomponente1`
    FOREIGN KEY (`Art_ID`)
    REFERENCES `mydb`.`tblKomponentenart` (`Art_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblKomponentenart_has_tblKomponentenattribut_tblKomponente2`
    FOREIGN KEY (`Attribut_ID`)
    REFERENCES `mydb`.`tblKomponentenattribut` (`Attribut_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblZuordnung_Attr_Komp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tblZuordnung_Attr_Komp` (
  `Attribut_ID` INT NOT NULL COMMENT '',
  `Komponent_ID` INT NOT NULL COMMENT '',
  `Wert` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`Attribut_ID`, `Komponent_ID`)  COMMENT '',
  INDEX `fk_tblKomponentenattribut_has_tblKomponent_tblKomponent1_idx` (`Komponent_ID` ASC)  COMMENT '',
  INDEX `fk_tblKomponentenattribut_has_tblKomponent_tblKomponentenat_idx` (`Attribut_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_tblKomponentenattribut_has_tblKomponent_tblKomponentenattr1`
    FOREIGN KEY (`Attribut_ID`)
    REFERENCES `mydb`.`tblKomponentenattribut` (`Attribut_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblKomponentenattribut_has_tblKomponent_tblKomponent1`
    FOREIGN KEY (`Komponent_ID`)
    REFERENCES `mydb`.`tblKomponent` (`Komponent_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
